# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
---
apiVersion: v1
kind: Namespace
metadata:
  name: game-2048-lz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048-lz
  name: deployment-2048-lz
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048-lz
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048-lz
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - us-west-2-las-1a
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: app-2048-lz
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048-lz
  name: service-2048-lz
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048-lz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: game-2048-lz
  name: ingress-2048-lz
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: "subnet-04204d3cf6285495f"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-2048-lz
              port:
                number: 80
